artifact_location: /Users/amberm/PycharmProjects/MLops/04-deployment/web-service-mlflow/MLFLOW_TRACKING_URI/0
creation_time: 1689084901290
experiment_id: '0'
last_update_time: 1689084901290
lifecycle_stage: active
name: Default
