deployments:
- name: taxi_local_data
  entrypoint: 03-orchestration/3.4/orchestrate.py:main_flow
  work_pool:
    name: zoompool
- name: taxi_s3_data
  entrypoint: 03-orchestration/3.5/orchestrate_s3.py:main_flow_s3
  work_pool:
    name: zoompool